CRITICAL - 2022-05-31 00:15:07 --> Invalid file: admin/incidencia.php
#0 C:\laragon\www\CT_prueba\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('admin/incidenci...')
#1 C:\laragon\www\CT_prueba\system\Common.php(1089): CodeIgniter\View\View->render('admin/incidenci...', Array, true)
#2 C:\laragon\www\CT_prueba\app\Controllers\Admin\Admin.php(11): view('admin/incidenci...')
#3 C:\laragon\www\CT_prueba\system\CodeIgniter.php(832): App\Controllers\Admin\Admin->index()
#4 C:\laragon\www\CT_prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Admin))
#5 C:\laragon\www\CT_prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\laragon\www\CT_prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-05-31 01:43:25 --> Undefined variable: validar
#0 C:\laragon\www\CT_prueba\app\Controllers\Admin\Admin.php(19): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\laragon\\www\\...', 19, Array)
#1 C:\laragon\www\CT_prueba\system\CodeIgniter.php(832): App\Controllers\Admin\Admin->registrarUsuario()
#2 C:\laragon\www\CT_prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Admin))
#3 C:\laragon\www\CT_prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\laragon\www\CT_prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-31 01:52:11 --> Class 'App\Controllers\Admin\Usuario' not found
#0 C:\laragon\www\CT_prueba\system\CodeIgniter.php(832): App\Controllers\Admin\Admin->registrarUsuario()
#1 C:\laragon\www\CT_prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Admin))
#2 C:\laragon\www\CT_prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\laragon\www\CT_prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
ERROR - 2022-05-31 01:56:44 --> Duplicate entry 'dimas amaya' for key 'usuario'
CRITICAL - 2022-05-31 01:56:44 --> Duplicate entry 'dimas amaya' for key 'usuario'
#0 C:\laragon\www\CT_prueba\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `tb...', 0)
#1 C:\laragon\www\CT_prueba\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tb...')
#2 C:\laragon\www\CT_prueba\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tb...')
#3 C:\laragon\www\CT_prueba\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', Array, false)
#4 C:\laragon\www\CT_prueba\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\CT_prueba\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\CT_prueba\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\laragon\www\CT_prueba\system\BaseModel.php(658): CodeIgniter\Model->insert(Object(App\Entities\Usuario), false)
#8 C:\laragon\www\CT_prueba\app\Controllers\Admin\Admin.php(74): CodeIgniter\BaseModel->save(Object(App\Entities\Usuario))
#9 C:\laragon\www\CT_prueba\system\CodeIgniter.php(832): App\Controllers\Admin\Admin->registrarUsuario()
#10 C:\laragon\www\CT_prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Admin))
#11 C:\laragon\www\CT_prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\CT_prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-05-31 13:26:54 --> Argument 1 passed to App\Models\UsuarioModel::buscarRol() must be of the type string, null given, called in C:\laragon\www\CT_prueba\app\Controllers\Auth\Login.php on line 57
#0 C:\laragon\www\CT_prueba\app\Controllers\Auth\Login.php(57): App\Models\UsuarioModel->buscarRol(NULL)
#1 C:\laragon\www\CT_prueba\system\CodeIgniter.php(832): App\Controllers\Auth\Login->signin()
#2 C:\laragon\www\CT_prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\Login))
#3 C:\laragon\www\CT_prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\laragon\www\CT_prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-31 13:29:34 --> Argument 1 passed to App\Models\UsuarioModel::buscarRol() must be of the type string, null given, called in C:\laragon\www\CT_prueba\app\Controllers\Auth\Login.php on line 57
#0 C:\laragon\www\CT_prueba\app\Controllers\Auth\Login.php(57): App\Models\UsuarioModel->buscarRol(NULL)
#1 C:\laragon\www\CT_prueba\system\CodeIgniter.php(832): App\Controllers\Auth\Login->signin()
#2 C:\laragon\www\CT_prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\Login))
#3 C:\laragon\www\CT_prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\laragon\www\CT_prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-31 13:30:40 --> Undefined property: App\Controllers\Auth\Login::$configs
#0 C:\laragon\www\CT_prueba\app\Controllers\Auth\Login.php(79): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\laragon\\www\\...', 79, Array)
#1 C:\laragon\www\CT_prueba\system\CodeIgniter.php(832): App\Controllers\Auth\Login->signin()
#2 C:\laragon\www\CT_prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\Login))
#3 C:\laragon\www\CT_prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\laragon\www\CT_prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-31 13:31:23 -->  route cannot be found while reverse-routing.
#0 C:\laragon\www\CT_prueba\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\laragon\www\CT_prueba\app\Controllers\Auth\Login.php(86): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\laragon\www\CT_prueba\system\CodeIgniter.php(832): App\Controllers\Auth\Login->signin()
#3 C:\laragon\www\CT_prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\Login))
#4 C:\laragon\www\CT_prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\laragon\www\CT_prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-05-31 13:32:41 -->  route cannot be found while reverse-routing.
#0 C:\laragon\www\CT_prueba\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\laragon\www\CT_prueba\app\Controllers\Auth\Login.php(86): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\laragon\www\CT_prueba\system\CodeIgniter.php(832): App\Controllers\Auth\Login->signin()
#3 C:\laragon\www\CT_prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\Login))
#4 C:\laragon\www\CT_prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\laragon\www\CT_prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-05-31 13:33:40 -->  route cannot be found while reverse-routing.
#0 C:\laragon\www\CT_prueba\system\HTTP\RedirectResponse.php(56): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\laragon\www\CT_prueba\app\Controllers\Auth\Login.php(86): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\laragon\www\CT_prueba\system\CodeIgniter.php(832): App\Controllers\Auth\Login->signin()
#3 C:\laragon\www\CT_prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\Login))
#4 C:\laragon\www\CT_prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\laragon\www\CT_prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-05-31 13:37:36 --> Argument 1 passed to App\Models\UsuarioModel::buscarRol() must be of the type string, null given, called in C:\laragon\www\CT_prueba\app\Controllers\Auth\Login.php on line 55
#0 C:\laragon\www\CT_prueba\app\Controllers\Auth\Login.php(55): App\Models\UsuarioModel->buscarRol(NULL)
#1 C:\laragon\www\CT_prueba\system\CodeIgniter.php(832): App\Controllers\Auth\Login->signin()
#2 C:\laragon\www\CT_prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\Login))
#3 C:\laragon\www\CT_prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\laragon\www\CT_prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-31 13:37:58 --> Argument 1 passed to App\Models\UsuarioModel::buscarRol() must be of the type int, null given, called in C:\laragon\www\CT_prueba\app\Controllers\Auth\Login.php on line 55
#0 C:\laragon\www\CT_prueba\app\Controllers\Auth\Login.php(55): App\Models\UsuarioModel->buscarRol(NULL)
#1 C:\laragon\www\CT_prueba\system\CodeIgniter.php(832): App\Controllers\Auth\Login->signin()
#2 C:\laragon\www\CT_prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\Login))
#3 C:\laragon\www\CT_prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\laragon\www\CT_prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-31 13:41:22 --> Argument 1 passed to App\Models\UsuarioModel::buscarRol() must be of the type string, null given, called in C:\laragon\www\CT_prueba\app\Controllers\Auth\Login.php on line 55
#0 C:\laragon\www\CT_prueba\app\Controllers\Auth\Login.php(55): App\Models\UsuarioModel->buscarRol(NULL)
#1 C:\laragon\www\CT_prueba\system\CodeIgniter.php(832): App\Controllers\Auth\Login->signin()
#2 C:\laragon\www\CT_prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\Login))
#3 C:\laragon\www\CT_prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\laragon\www\CT_prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-31 13:41:52 --> Argument 1 passed to App\Models\UsuarioModel::buscarRol() must be of the type string, null given, called in C:\laragon\www\CT_prueba\app\Controllers\Auth\Login.php on line 55
#0 C:\laragon\www\CT_prueba\app\Controllers\Auth\Login.php(55): App\Models\UsuarioModel->buscarRol(NULL)
#1 C:\laragon\www\CT_prueba\system\CodeIgniter.php(832): App\Controllers\Auth\Login->signin()
#2 C:\laragon\www\CT_prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\Login))
#3 C:\laragon\www\CT_prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\laragon\www\CT_prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-31 13:42:02 --> Argument 1 passed to App\Models\UsuarioModel::buscarRol() must be of the type string, null given, called in C:\laragon\www\CT_prueba\app\Controllers\Auth\Login.php on line 55
#0 C:\laragon\www\CT_prueba\app\Controllers\Auth\Login.php(55): App\Models\UsuarioModel->buscarRol(NULL)
#1 C:\laragon\www\CT_prueba\system\CodeIgniter.php(832): App\Controllers\Auth\Login->signin()
#2 C:\laragon\www\CT_prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\Login))
#3 C:\laragon\www\CT_prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\laragon\www\CT_prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-31 13:42:17 --> Argument 1 passed to App\Models\UsuarioModel::buscarRol() must be of the type string, null given, called in C:\laragon\www\CT_prueba\app\Controllers\Auth\Login.php on line 55
#0 C:\laragon\www\CT_prueba\app\Controllers\Auth\Login.php(55): App\Models\UsuarioModel->buscarRol(NULL)
#1 C:\laragon\www\CT_prueba\system\CodeIgniter.php(832): App\Controllers\Auth\Login->signin()
#2 C:\laragon\www\CT_prueba\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\Login))
#3 C:\laragon\www\CT_prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\laragon\www\CT_prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-05-31 23:59:18 --> roles filter must have a matching alias defined.
#0 C:\laragon\www\CT_prueba\system\Filters\Filters.php(340): CodeIgniter\Filters\Exceptions\FilterException::forNoAlias('roles')
#1 C:\laragon\www\CT_prueba\system\CodeIgniter.php(384): CodeIgniter\Filters\Filters->enableFilter('roles', 'before')
#2 C:\laragon\www\CT_prueba\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\laragon\www\CT_prueba\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
